//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogPostManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.Comment_Reaction = new HashSet<Comment_Reaction>();
        }
    
        public int Id { get; set; }
        public string Comment_Title { get; set; }
        public Nullable<int> Blog_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Reaction> Comment_Reaction { get; set; }
    }
}
